services:
  cf:
    image: ghcr.io/silencebay/better-cloudflare-ip:latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    command: run
    environment:
      - CRON=0 */6 * * *
      - BANDWIDTH=20
      - ENABLED_TASKS=unpack_cloudflare_geoip,test,gist,dispatch
      - DISPATCH_TOKEN=${GITHUB_TOKEN}
      - DISPATCH_REPO=${GITHUB_REPO}
      - DISPATCH_OWNER=${GITHUB_OWNER}
      - DISPATCH_WORKFLOW=${GITHUB_WORKFLOW:-main.yml}
      - DISPATCH_REF=${GITHUB_REF:-main}
      - DISPATCH_INPUTS=${GITHUB_INPUTS:-"{}"}
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
      - ./tasks:/app/tasks:ro
    # healthcheck:
    #   test: ["CMD", "pgrep", "crond"]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3
