services:
  cf:
    image: ghcr.io/silencebay/better-cloudflare-ip:latest
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    command: run
    environment:
      - CRON=0 */6 * * *
      - ENABLED_TASKS=unpack_cloudflare_geoip,test,gist,dispatch
      - TOP_N=10
      - OUTPUT_DIR=/data
      - V2DAT_URL=https://github.com/m0xbf/v2dat/releases/download/v20240712/v2dat_20240712_amd64
      - CLOUDFLARE_GEOIP_URL=https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat          
      - DISPATCH_TOKEN=${GITHUB_TOKEN}
      - DISPATCH_REPO=${GITHUB_REPO}
      - DISPATCH_OWNER=${GITHUB_OWNER}
      - DISPATCH_WORKFLOW=${GITHUB_WORKFLOW:-main.yml}
      - DISPATCH_REF=${GITHUB_REF:-main}
      - DISPATCH_INPUTS=${GITHUB_INPUTS:-"{}"}
      - GIST_TOKEN=${GITHUB_TOKEN}
      - GIST_ID=${GIST_ID}
      - GIST_INPUT_FILES=/data/ips-v4.txt,/data/ips-v6.txt
      - GIST_FILENAME=cloudflare-ips-v4.txt,cloudflare-ips-v6.txt
      - GIST_MERGE_FILENAME=cloudflare-ips.txt
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
      - ./tasks:/app/tasks:ro
    # healthcheck:
    #   test: ["CMD", "pgrep", "crond"]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3
